# Generated by Django 4.1.7 on 2023-03-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('name', models.CharField(max_length=20)),
                ('price', models.FloatField(max_length=4)),
                ('author', models.CharField(max_length=30)),
            ],
        ),
    ]
