# Generated by Django 4.1.7 on 2023-04-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateField(auto_created=True)),
                ('post_name', models.TextField(max_length=10)),
                ('post_poster', models.FileField(upload_to='amanbhai_work')),
            ],
        ),
    ]
