# Generated by Django 4.1.7 on 2023-04-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postwork',
            name='post_poster',
            field=models.FileField(upload_to='static/amanbhai_work'),
        ),
    ]
