# Generated by Django 4.1.7 on 2023-04-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_postwork_post_disc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postwork',
            name='post_disc',
            field=models.TextField(max_length=150),
        ),
    ]
